USE [TPC-H_500]
GO
--Create all Tables without PK / FK contraints
DROP TABLE IF EXISTS CUSTOMER
GO

CREATE TABLE [dbo].[CUSTOMER](
	[C_CUSTKEY] [int] NOT NULL,
	[C_NAME] [varchar](25) NOT NULL,
	[C_ADDRESS] [varchar](40) NOT NULL,
	[C_NATIONKEY] [int] NOT NULL,
	[C_PHONE] [char](15) NOT NULL,
	[C_ACCTBAL] [decimal](15, 2) NOT NULL,
	[C_MKTSEGMENT] [char](10) NOT NULL,
	[C_COMMENT] [varchar](117) NOT NULL
)
ON SECONDARY;
GO

DROP TABLE IF EXISTS LINEITEM
GO

CREATE TABLE [dbo].[LINEITEM](
	[L_ORDERKEY] [int] NOT NULL,
	[L_PARTKEY] [int] NOT NULL,
	[L_SUPPKEY] [int] NOT NULL,
	[L_LINENUMBER] [int] NOT NULL,
	[L_QUANTITY] [decimal](15, 2) NOT NULL,
	[L_EXTENDEDPRICE] [decimal](15, 2) NOT NULL,
	[L_DISCOUNT] [decimal](15, 2) NOT NULL,
	[L_TAX] [decimal](15, 2) NOT NULL,
	[L_RETURNFLAG] [char](1) NOT NULL,
	[L_LINESTATUS] [char](1) NOT NULL,
	[L_SHIPDATE] [date] NOT NULL,
	[L_COMMITDATE] [date] NOT NULL,
	[L_RECEIPTDATE] [date] NOT NULL,
	[L_SHIPINSTRUCT] [char](25) NOT NULL,
	[L_SHIPMODE] [char](10) NOT NULL,
	[L_COMMENT] [varchar](44) NOT NULL
)
ON LINEITEM;
GO

DROP TABLE IF EXISTS NATION
GO

CREATE TABLE [dbo].[NATION](
	[N_NATIONKEY] [int] NOT NULL,
	[N_NAME] [char](25) NOT NULL,
	[N_REGIONKEY] [int] NOT NULL,
	[N_COMMENT] [varchar](152) NULL
)
ON SECONDARY;
GO

DROP TABLE IF EXISTS ORDERS
GO
CREATE TABLE [dbo].[ORDERS](
	[O_ORDERKEY] [int] NOT NULL,
	[O_CUSTKEY] [int] NOT NULL,
	[O_ORDERSTATUS] [char](1) NOT NULL,
	[O_TOTALPRICE] [decimal](15, 2) NOT NULL,
	[O_ORDERDATE] [date] NOT NULL,
	[O_ORDERPRIORITY] [char](15) NOT NULL,
	[O_CLERK] [char](15) NOT NULL,
	[O_SHIPPRIORITY] [int] NOT NULL,
	[O_COMMENT] [varchar](79) NOT NULL
)
ON Orders;
GO

DROP TABLE IF EXISTS PART
GO
CREATE TABLE [dbo].[PART](
	[P_PARTKEY] [int] NOT NULL,
	[P_NAME] [varchar](55) NOT NULL,
	[P_MFGR] [char](25) NOT NULL,
	[P_BRAND] [char](10) NOT NULL,
	[P_TYPE] [varchar](25) NOT NULL,
	[P_SIZE] [int] NOT NULL,
	[P_CONTAINER] [char](10) NOT NULL,
	[P_RETAILPRICE] [decimal](15, 2) NOT NULL,
	[P_COMMENT] [varchar](23) NOT NULL
)
ON SECONDARY;
GO

DROP TABLE IF EXISTS PARTSUPP
GO

CREATE TABLE [dbo].[PARTSUPP](
	[PS_PARTKEY] [int] NOT NULL,
	[PS_SUPPKEY] [int] NOT NULL,
	[PS_AVAILQTY] [int] NOT NULL,
	[PS_SUPPLYCOST] [decimal](15, 2) NOT NULL,
	[PS_COMMENT] [varchar](199) NOT NULL
)
ON PARTSUPP;
GO

DROP TABLE IF EXISTS REGION
GO
CREATE TABLE [dbo].[REGION](
	[R_REGIONKEY] [int] NOT NULL,
	[R_NAME] [char](25) NOT NULL,
	[R_COMMENT] [varchar](152) NULL
)
ON SECONDARY;
GO

DROP TABLE IF EXISTS SUPPLIER
GO
CREATE TABLE [dbo].[SUPPLIER](
	[S_SUPPKEY] [int] NOT NULL,
	[S_NAME] [char](25) NOT NULL,
	[S_ADDRESS] [varchar](40) NOT NULL,
	[S_NATIONKEY] [int] NOT NULL,
	[S_PHONE] [char](15) NOT NULL,
	[S_ACCTBAL] [decimal](15, 2) NOT NULL,
	[S_COMMENT] [varchar](101) NOT NULL
)
ON SECONDARY;
GO

