-- Cleanup
ALTER RESOURCE GOVERNOR with (CLASSIFIER_FUNCTION = NULL)
GO
ALTER RESOURCE GOVERNOR RECONFIGURE
GO

DROP FUNCTION fnUserClassifier
GO

DROP WORKLOAD GROUP Customer1Group
DROP WORKLOAD GROUP Customer2Group
GO

DROP RESOURCE POOL Customer1Pool
DROP RESOURCE POOL Customer2Pool
GO


Truncate Table Customer1DB..NewTable