USE [master]
GO
CREATE SERVER AUDIT [TestingUserDefinedEvents]
TO FILE
( FILEPATH = N'C:\SQLAUDITS'
,MAXSIZE = 5 MB
,MAX_ROLLOVER_FILES = 5
,RESERVE_DISK_SPACE = OFF
)
WITH
( QUEUE_DELAY = 1000
,ON_FAILURE = CONTINUE
)
GO
ALTER SERVER AUDIT [TestingUserDefinedEvents] WITH (STATE = ON);
GO
USE [AdventureWorks2016]
GO
CREATE DATABASE AUDIT SPECIFICATION [LargePayIncrease]
FOR SERVER AUDIT [TestingUserDefinedEvents]
ADD (USER_DEFINED_AUDIT_GROUP)
WITH (STATE = ON)
GO